// swift-tools-version: 5.9
// This file is generated by ci/generateIosSpmPackage.sh in last9/browser.
// Do not edit by hand — changes are overwritten on the next release.
import PackageDescription

let package = Package(
    name: "Last9RUM",
    platforms: [
        .iOS("15.1"),
    ],
    products: [
        .library(
            name: "Last9RUM",
            targets: ["Last9RUM"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "Last9RUM",
            url: "https://cdn.last9.io/rum-sdk/ios/builds/1.6.9-alpha.33558194984/Last9RUM.xcframework.zip",
            checksum: "13b83300298b3c3c0e4daddb26e3450a0fcfdd2128ff14eab278040af79ae29b"
        ),
    ]
)
