// swift-tools-version: 5.9
// This file is generated by ci/generateIosSpmPackage.sh in last9/browser.
// Do not edit by hand — changes are overwritten on the next release.
import PackageDescription

let package = Package(
    name: "Last9RUM",
    platforms: [
        .iOS("15.1"),
    ],
    products: [
        .library(
            name: "Last9RUM",
            targets: ["Last9RUM"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "Last9RUM",
            url: "https://cdn.last9.io/rum-sdk/ios/builds/1.9.0-alpha.36377788525/Last9RUM.xcframework.zip",
            checksum: "850de0d79907a2d4fdeb660e496fe75c9ac20fd5846cdff714c076faf3d9b426"
        ),
    ]
)
