// swift-tools-version: 5.9
// This file is generated by ci/generateIosSpmPackage.sh in last9/browser.
// Do not edit by hand — changes are overwritten on the next release.
import PackageDescription

let package = Package(
    name: "Last9RUM",
    platforms: [
        .iOS("15.1"),
    ],
    products: [
        .library(
            name: "Last9RUM",
            targets: ["Last9RUM"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "Last9RUM",
            url: "https://cdn.last9.io/rum-sdk/ios/builds/1.6.9-alpha.33722172698/Last9RUM.xcframework.zip",
            checksum: "b214771ea592e627b730244244c0771a7b8eaed3c45d10c0f0ac827570aac455"
        ),
    ]
)
